# Generated by Django 3.0.4 on 2020-03-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', related_query_name='publicacao', to='core.Categoria'),
        ),
    ]
